/* Sonobi - Morpheus version: 3.26.3 */
(function(){var y="function"==typeof Object.defineProperties?Object.defineProperty:function(m,k,l){m!=Array.prototype&&m!=Object.prototype&&(m[k]=l.value)},z="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global&&null!=global?global:this;function B(){B=function(){};z.Symbol||(z.Symbol=G)}var H=0;function G(m){return"jscomp_symbol_"+(m||"")+H++}
function I(){B();var m=z.Symbol.iterator;m||(m=z.Symbol.iterator=z.Symbol("iterator"));"function"!=typeof Array.prototype[m]&&y(Array.prototype,m,{configurable:!0,writable:!0,value:function(){return J(this)}});I=function(){}}function J(m){var k=0;return K(function(){return k<m.length?{done:!1,value:m[k++]}:{done:!0}})}function K(m){I();m={next:m};m[z.Symbol.iterator]=function(){return this};return m}function L(m){I();B();I();var k=m[Symbol.iterator];return k?k.call(m):J(m)}
function O(m){for(var k,l=[];!(k=m.next()).done;)l.push(k.value);return l}function P(m){return m instanceof Array?m:O(L(m))}function Q(m,k){if(k){var l=z;m=m.split(".");for(var c=0;c<m.length-1;c++){var e=m[c];e in l||(l[e]={});l=l[e]}m=m[m.length-1];c=l[m];k=k(c);k!=c&&null!=k&&y(l,m,{configurable:!0,writable:!0,value:k})}}
Q("Promise",function(m){function k(a){this.D=0;this.J=void 0;this.C=[];var b=this.F();try{a(b.resolve,b.reject)}catch(h){b.reject(h)}}function l(){this.C=null}function c(a){return a instanceof k?a:new k(function(b){b(a)})}if(m)return m;l.prototype.D=function(a){this.C||(this.C=[],this.H());this.C.push(a)};l.prototype.H=function(){var a=this;this.F(function(){a.L()})};var e=z.setTimeout;l.prototype.F=function(a){e(a,0)};l.prototype.L=function(){for(;this.C&&this.C.length;){var a=this.C;this.C=[];for(var b=
0;b<a.length;++b){var h=a[b];delete a[b];try{h()}catch(p){this.J(p)}}}this.C=null};l.prototype.J=function(a){this.F(function(){throw a;})};k.prototype.F=function(){function a(a){return function(g){h||(h=!0,a.call(b,g))}}var b=this,h=!1;return{resolve:a(this.pa),reject:a(this.H)}};k.prototype.pa=function(a){if(a===this)this.H(new TypeError("A Promise cannot resolve to itself"));else if(a instanceof k)this.va(a);else{a:switch(typeof a){case "object":var b=null!=a;break a;case "function":b=!0;break a;
default:b=!1}b?this.ca(a):this.L(a)}};k.prototype.ca=function(a){var b=void 0;try{b=a.then}catch(h){this.H(h);return}"function"==typeof b?this.wa(b,a):this.L(a)};k.prototype.H=function(a){this.U(2,a)};k.prototype.L=function(a){this.U(1,a)};k.prototype.U=function(a,b){if(0!=this.D)throw Error("Cannot settle("+a+", "+b|"): Promise already settled in state"+this.D);this.D=a;this.J=b;this.ba()};k.prototype.ba=function(){if(this.C){for(var a=this.C,b=0;b<a.length;++b)a[b].call(),a[b]=null;this.C=null}};
var a=new l;k.prototype.va=function(a){var b=this.F();a.za(b.resolve,b.reject)};k.prototype.wa=function(a,b){var h=this.F();try{a.call(b,h.resolve,h.reject)}catch(p){h.reject(p)}};k.prototype.then=function(a,b){function h(a,b){return"function"==typeof a?function(b){try{p(a(b))}catch(C){g(C)}}:b}var p,g,d=new k(function(a,b){p=a;g=b});this.za(h(a,p),h(b,g));return d};k.prototype.catch=function(a){return this.then(void 0,a)};k.prototype.za=function(c,b){function h(){switch(p.D){case 1:c(p.J);break;
case 2:b(p.J);break;default:throw Error("Unexpected state: "+p.D);}}var p=this;this.C?this.C.push(function(){a.D(h)}):a.D(h)};k.resolve=c;k.reject=function(a){return new k(function(b,h){h(a)})};k.race=function(a){return new k(function(b,h){for(var p=L(a),g=p.next();!g.done;g=p.next())c(g.value).za(b,h)})};k.all=function(a){var b=L(a),h=b.next();return h.done?c([]):new k(function(a,g){function d(b){return function(d){f[b]=d;q--;q||a(f)}}var f=[],q=0;do f.push(void 0),q++,c(h.value).za(d(f.length-1),
g),h=b.next();while(!h.done)})};return k});Q("Number.MAX_SAFE_INTEGER",function(){return 9007199254740991});Q("Array.from",function(m){return m?m:function(k,l,c){I();l=l?l:function(a){return a};var e=[],a=k[Symbol.iterator];if("function"==typeof a)for(k=a.call(k);!(a=k.next()).done;)e.push(l.call(c,a.value));else{a=k.length;for(var n=0;n<a;n++)e.push(l.call(c,k[n]))}return e}});
Q("Object.assign",function(m){return m?m:function(k,l){for(var c=1;c<arguments.length;c++){var e=arguments[c];if(e)for(var a in e)Object.prototype.hasOwnProperty.call(e,a)&&(k[a]=e[a])}return k}});Q("Array.prototype.find",function(m){return m?m:function(k,l){a:{var c=this;c instanceof String&&(c=String(c));for(var e=c.length,a=0;a<e;a++){var n=c[a];if(k.call(l,n,a,c)){k=n;break a}}k=void 0}return k}});Q("Object.is",function(m){return m?m:function(k,l){return k===l?0!==k||1/k===1/l:k!==k&&l!==l}});
Q("Array.prototype.includes",function(m){return m?m:function(k,l){var c=this;c instanceof String&&(c=String(c));var e=c.length;for(l=l||0;l<e;l++)if(c[l]==k||Object.is(c[l],k))return!0;return!1}});
Q("String.prototype.includes",function(m){return m?m:function(k,l){if(null==this)throw new TypeError("The 'this' value for String.prototype.includes must not be null or undefined");if(k instanceof RegExp)throw new TypeError("First argument to String.prototype.includes must not be a regular expression");return-1!==(this+"").indexOf(k,l||0)}});
(function(m,k){(function(l){function c(a){if(e[a])return e[a].ra;var n=e[a]={jd:a,vc:!1,ra:{}};l[a].call(n.ra,n,n.ra,c);n.vc=!0;return n.ra}var e={};c.H=l;c.F=e;c.C=function(a,e){c.D(a)||Object.defineProperty(a,"a",{configurable:!1,enumerable:!0,get:e})};c.J=function(a){var e=a&&a.Mc?function(){return a["default"]}:function(){return a};c.C(e,e);return e};c.D=function(a){return Object.prototype.hasOwnProperty.call(a,"a")};c.L="";return c(c.U=7)})([function(l,c,e){l=e(11);e=window;Object(l.a)(e);c.a=
e},function(l,c,e){function a(a){var b={};a.forEach(function(a){b[a.K]=b[a.K]||[];b[a.K]=b[a.K].concat(a)});return b}function n(){return v.a.location.origin?v.a.location.origin:v.a.location.origin=v.a.location.protocol+"//"+v.a.location.hostname+(v.a.location.ia?":"+v.a.location.ia:"")}function b(a){var b=!1;return function(d){for(var E=[],f=0;f<arguments.length;++f)E[f-0]=arguments[f];if(!b){b=!0;try{a.apply(a,E)}catch(M){}}}}function h(a){a=void 0===a?[]:a;if(!Array.isArray(a))return[];a=Array.from(a);
for(var b=a.length;b;b--){var d=Math.floor(Math.random()*b),f=L([a[d],a[b-1]]);a[b-1]=f.next().value;a[d]=f.next().value}return a}function p(a,b){b=void 0===b?F().location:b;b=decodeURI(b);a=a.replace(/[\[\]]/g,"\\$&");return(a=(new RegExp("[?&]"+a+"(=([^&#]*)|&|#|$)")).exec(b))?a[2]?decodeURIComponent(a[2].replace(/\+/g," ")):"":null}function g(a){return parseInt(a,10)}function d(a,b){var f;if(b&&"string"===typeof b){if(-1!==b.indexOf(".")){b=b.split(".");for(var g=!1,E=0;E<b.length;E++){if("object"!==
typeof a){g=!0;break}a=d(a,b[E])}g||(f=a);return f}g="get"+b[0].toUpperCase()+b.slice(1);b=a&&"function"===typeof a[g]?g:b;a&&(a.hasOwnProperty(b)||"function"===typeof a[b])&&(f="function"===typeof a[b]?a[b]():a[b]);return f}}function f(a){return a?'<script type="text/javascript" src="'+a+'">\x3c/script>':""}function q(a,b){if(!a)return"";b=b.split("x");return'<iframe id="'+t()+'" width="'+b[0]+'" '+('height="'+b[1]+'" marginwidth="0" marginheight="0" ')+('style="border:0" frameborder="0" src="'+
a+'" border="0" ')+'scrolling="no" vspace="0" hspace="0"></iframe>'}function u(a){return a?'<div style="position:absolute;left:0px;top:0px;visibility:hidden;">'+('<img src="'+a+'"></div>'):""}function C(a,b){var d=[];a.forEach(function(a){-1!==b.indexOf(a)&&d.push(a)});return d}function w(){return[v.a.innerWidth||v.a.document.documentElement.clientWidth||v.a.document.body.clientWidth,v.a.innerHeight||v.a.document.documentElement.clientHeight||v.a.document.body.clientHeight]}function x(a,b){a=Math.round(a);
for(var d=0;d<b.length;d++){var f="lt"in b[d]&&a<b[d].lt||!("lt"in b[d]);!("ge"in b[d]&&a>=b[d].ge)&&"ge"in b[d]||!f||"percent"in b[d]&&(a*=b[d].percent)}for(d=0;d<b.length;d++)f="lt"in b[d]&&a<b[d].lt||!("lt"in b[d]),!("ge"in b[d]&&a>=b[d].ge)&&"ge"in b[d]||!f||("set"in b[d]?a=b[d].set:"round"in b[d]&&(a=Math.floor(a)-Math.floor(a)%b[d].round));return a}function r(a,b,d){Object.keys(b).forEach(function(f){a=a.replace(d+f+d,b[f])});return a}function t(){return m()+Math.random().toString(16).substr(2)}
function F(a){a=void 0===a?"":a;var b=v.a.document.createElement("a");b.href=a||v.a.location;return{location:b.href,href:b.href,protocol:b.protocol,hostname:b.hostname,host:b.host,ia:b.ia,pathname:b.pathname,search:b.search,la:b.la,origin:b.origin}}function D(a){return Object.keys(a).map(function(b){return Array.isArray(a[b])?a[b].map(function(a){return b+"[]="+a}).join("&"):b+"="+a[b]}).join("&")}c.g=D;var v=e(0),k=e(2),m=function(){var a=0;return function(){a++;return a}}();c.j=t;c.n=r;l={highestCPMWins:function(a,
b){if(0===a.length)return null;for(var d={I:0},f=0;f<a.length;f++)d.I>=a[f].I?b.log("sbi",k.q,[a[f].I,a[f].P]):d=a[f];return d.I?d:null},sonobiDealWinsOverHighestCPM:function(a,b){if(0===a.length)return null;for(var d={I:0,P:null,W:null},f=0;f<a.length;f++)if(10<=a[f].ka)a[f].I>d.I&&(b.log("sbi",k.q,[d.I,d.P]),d=a[f]);else{if("sonobi"===a[f].P&&a[f].W){d=a[f];a.forEach(function(g){g!==d&&b.log("sbi",k.q,[a[f].I,a[f].P])});break}d.I>=a[f].I?b.log("sbi",k.q,[a[f].I,a[f].P]):d=a[f]}return d.I||d.W?d:
null},lowestDealPriorityWinsOverHighestCPM:function(a,b){if(0===a.length)return null;a.sort(function(a,b){return a.ka-b.ka});var d=a[0].ka,f=a.filter(function(a){return a.ka===d});a={I:0,P:null,W:null};f=L(f);for(var g=f.next();!g.done;g=f.next())g=g.value,a.I>=g.I?b.log("sbi",k.q,[g.I,g.P]):a=g;return a.I||a.W?a:null}};c.a=l;c.b=x;c.k=w;c.f=C;c.l=d;c.i=p;c.c=h;c.m=b;c.h=n;c.d=a;c.e={ad:function(a,b){return a.reduce(function(a,d){return a.then(function(a){return b(d).then(a.push.bind(a)).then(function(){return a})})},
Promise.resolve([]))},Q:F,Za:t,fd:function(a){if(a){try{var b=a.contentWindow?a.contentWindow.document:a.pb.document?a.pb.document:a.pb}catch(S){return}return b}},ed:function(){var a=v.a.document.createElement("iframe");a.id=t();a.height=0;a.width=0;a.hspace="0";a.vspace="0";a.marginWidth="0";a.marginHeight="0";a.style.border="0";a.frameBorder="0";a.border="0px";a.scrolling="no";a.src="about:blank";a.style.display="none";return a},ud:r,pd:function(a,b){for(var d=0,f=a.length>b.length?b.length:a.length,
g=a.length<b.length?b.length:a.length,t=0;t<f;t++)a[t]===b[t]&&d++;return d/g},Lc:l,Nc:x,hd:w,Yc:C,bd:D,lc:function(a){try{var b=new RegExp(a,"i"),d=v.a.performance.getEntriesByType("resource").filter(function(a){return b.test(a.name)});return Array.isArray(d)?Math.max(d[d.length-1].Wc||0,0):null}catch(T){return null}},ab:function(a){return void 0!=={sizes:1,timeout:1}[a]},Da:function(a){var b=v.a.innerWidth,d=null,f;for(f in a)if(a.hasOwnProperty(f)){var g=a[f].viewport.lt||Number.MAX_SAFE_INTEGER;
if(b>=(a[f].viewport.ge||0)&&b<g){d=f;break}}return d},qc:function(a,b){return a.reduce(function(a,d){(a[d[b]]=a[d[b]]||[]).push(d);return a},{})},Uc:u,Sc:q,Tc:f,dc:function(a,b,d){switch(void 0===b?"SCRIPT":b){case "SCRIPT":return f(a);case "IFRAME":return q(a,void 0===d?"1x1":d);case "TRACK":return u(a);case "SCRIPT_BLOCK":return a?'<script type="text/javascript">'+a+"\x3c/script>":"";default:return""}},ha:d,Rc:function(a){var b=/^\d{1,4}x\d{1,4}$/;return"string"===typeof a&&b.test(a)?a.split("x").map(g):
a},zc:function(a,b){var d={},f;for(f in a)-1===b.indexOf(f)&&(d[f]=a[f]);return d},zb:function(a){try{return"string"!==typeof a?void 0:v.a.document.cookie.split("; ").reduce(function(a,b){var d=L(b.split("="));b=d.next().value;d=O(d);a[b]=d.join("=");return a},{})[a]}catch(R){}},mc:p,Oc:h,Fc:function(a){void 0!==v.a.performance&&"function"===typeof v.a.performance.setResourceTimingBufferSize&&v.a.performance.setResourceTimingBufferSize(a)},$:b,sc:function(a,b){a=void 0===a?[]:a;b=void 0===b?[]:b;
return a.reduce(function(a,d){-1===a.indexOf(d)&&-1<b.indexOf(d)&&a.push(d);return a},[])},ub:function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;return("x"===a?b:b&3|8).toString(16)})},uc:function(a,b){var d={},f;for(f in a)-1!==b.indexOf(f)&&(d[f]=a[f]);return d},dd:n,Qc:a}},function(l,c){c.x=200001;c.n=200003;c.A=200005;c.w=200006;c.d=200008;c.m=200009;c.e=200011;c.k=200012;c.q=200017;c.B=200019;c.o=200020;c.f=200022;c.c=200023;c.b=200024;
c.a=200025;c.g=200026;c.y=200027;c.z=200028;c.s=200029;c.i=200030;c.h=200031;c.v=200032;c.t=200033;c.l=200034;c.j=200035;c.p=200036;c.r=200039;c.u=200040},function(l,c,e){function a(a){return a?a.replace(/^\?/,"").split("&").reduce(function(a,b){var d=L(b.split("="));b=d.next().value;d=d.next().value;/\[\]$/.test(b)?(b=b.replace("[]",""),a[b]=a[b]||[],a[b].push(d)):a[b]=d||"";return a},{}):{}}function n(b){var d=h.a.document.createElement("a");d.href=decodeURIComponent(b);return{protocol:(d.protocol||
"").replace(/:$/,""),hostname:d.hostname,ia:+d.ia,pathname:d.pathname,search:a(d.search||""),la:(d.la||"").replace(/^#/,""),host:d.host}}function b(a){return(a.protocol||"http")+"://"+(a.host||a.hostname+(a.ia?":"+a.ia:""))+(a.pathname||"")+(a.search?"?"+Object(p.g)(a.search||""):"")+(a.la?"#"+a.la:"")}var h=e(0),p=e(1);c.a={Kc:3E4,od:function(a,b,f,q){var d=this;f=void 0===f?"sbi_"+Object(p.j)():f;q=void 0===q?{}:q;a=a.replace("%%callback%%",f);return new Promise(function(g){var u=h.a.setTimeout(g,
d.Kc,q),c,r=Object(p.m)(function(a){h.a.clearTimeout(c);h.a.clearTimeout(u);if(null==b)g(a);else{var d={};d[b]=a;g(d)}});h.a[f]=r;d.Aa("script",{src:a}).then(function(){c=h.a.setTimeout(function(){r(q)},500)})})},Sa:function(a,d,f){f=void 0===f?{Db:"GET",withCredentials:!1,Ac:!1,cc:"text/plain"}:f;return new Promise(function(g,u){function q(){4===r.readyState&&(200<=r.status&&400>r.status?g(r.responseText):u({status:r.status,statusText:r.statusText}))}var c=f.Db||(d?"POST":"GET"),p=h.a.XDomainRequest&&
(!h.a.XMLHttpRequest||void 0===(new h.a.XMLHttpRequest).responseType);if(p){var r=new h.a.XDomainRequest;r.onload=function(){g(r.responseText)};r.onerror=function(){u("xhr on error")};r.ontimeout=function(){u("xhr timeout")};r.onprogress=function(){}}else r=new h.a.XMLHttpRequest,r.onreadystatechange=q;if("GET"===c&&d){var t=n(a);Object.assign(t.search,d);a=b(t)}r.open(c,a);p||(f.withCredentials&&(r.withCredentials=!0),f.Ac&&r.setRequestHeader("X-Requested-With","XMLHttpRequest"),r.setRequestHeader("Content-Type",
f.cc||"text/plain"));r.send("POST"===c&&d)})},Aa:function(a,b){return new Promise(function(d,g){if("image"===a)var f=Object.assign(new h.a.Image,b);else if("script"===a||" iframe"===a)f=h.a.document.createElement(a),Object.keys(b||{}).forEach(function(a){f[a]=b[a]}),h.a.document.head.appendChild(f);else{g();return}f.addEventListener?f.addEventListener("load",function(){d()}):f.readyState?f.onreadystatechange=function(){3===f.readyState&&d()}:g()})}}},function(l,c){function e(){this.C={}}e.prototype.fa=
function(a,c){for(var b=[],h=1;h<arguments.length;++h)b[h-1]=arguments[h];a in this.C&&(this.C[a].T.forEach(function(a){return a.apply(a,b)}),this.C[a].$.forEach(function(a){return a.apply(a,b)}),this.C[a].$=[])};e.prototype.$=function(a,c){this.C[a]=this.C[a]||{T:[],$:[]};this.C[a].$.push(c)};e.prototype.T=function(a,c){this.C[a]=this.C[a]||{T:[],$:[]};this.C[a].T.push(c)};e.prototype.Cc=function(a,c){this.C[a].T=this.C[a].T.filter(function(a){return a!==c});this.C[a].$=this.C[a].T.filter(function(a){return a!==
c})};c.a=new e;c.b=new e},function(l,c){function e(a){this.S=a.globalSettings}e.prototype.ga=function(a){return(a=void 0===a?null:a)?this.S[a]:this.S};c.a=e},function(l,c,e){function a(a){this.S=a.platformSettings;this.X=new n.a(a)}var n=e(5),b=e(1);a.prototype.sa=function(a,c){a=void 0===a?null:a;c=void 0===c?null:c;return a?(a=this.S[a],c&&(a=a[c],a=b.e.ab(c)&&!a?this.X.ga(c):a),a):this.S};c.a=a},function(l,c,e){l.ra=e(8)},function(l,c,e){Object.defineProperty(c,"__esModule",{value:!0});l=e(9);
e=e(0);c["default"]=Object(l.a)(e.a,m,k)},function(l,c,e){var a=e(10),n=e(12),b=e(14),h=e(23),p=e(24),g=e(26),d=e(27),f=e(1),q=e(28);c.a=function(c,e,w){if(!c.hasOwnProperty("sbi_km")||!c.sbi_km.apiReady){f.e.Fc(500);var u=c.sbi_morpheus=Object(d.a)();e=c.sbi_km=Object.assign({API:{},config:e,apiReady:!1,id:f.e.Za()},c.sbi_km);var r=new p.a(e.config),t=new a.a(e.config),F=new h.a(t,r),D=new b.a(t,F,r);D.rc(e.config);e.API=Object.assign(e.API,{debug:t.ec.bind(t),getLog:t.xb.bind(t)});t=new n.a(t,e.config,
D,F);(new q.a(D,t,r)).Bc();r=Object(g.a)(D,e.config,r.X.ga("timeout"),t,r,F);t.Jc(r.Dc);-1===c.location.search.indexOf("sbi_test")?c.document.cookie="sbi_debug=false":-1!==c.document.cookie.indexOf("sbi_debug=true")?e.API.debug(!0):-1!==c.location.search.indexOf("sbi_test")&&(c.document.cookie="sbi_debug=true",e.API.debug(!0));u.initialize();c.sbi_km.apiReady=!0;c.sbi_km.version=w}}},function(l,c,e){function a(a,g){var d=this;g=void 0===g?b.a:g;this.log=function(a,b,g,c){null!=c?c-=d.navigationStart:
c=0+n.a.performance.now();a={dateTime:c,time:c-0,id:b,service:a,replacements:g};a.Ib=g||[];h.push(a);d.C&&"logData"in n.a.sbi_km&&(g=n.a.sbi_km.logData,d.D(g[a.id].service,a.ib,g[a.id].template,a.Ib))};this.caller=g;this.config=a;this.C=!1;this.navigationStart=n.a.performance.timing.navigationStart}var n=e(0),b=e(3),h=[];a.prototype.xb=function(){h.sort(function(a,b){return a.ib-b.ib});return h};a.prototype.F=function(a,b){for(var d=[],f=1;f<arguments.length;++f)d[f-1]=arguments[f];n.a.console.log.apply(n.a.console,
[].concat(["sonobi",a],P(d)))};a.prototype.D=function(a,b,d,f){var g=[a,b];a=d.apply(d,f);Array.isArray(a)?a.forEach(function(a){return g.push(a)}):g.push(a);n.a.console.log.apply(n.a.console,g)};a.prototype.ec=function(){var a=this;this.C=!0;b.a.Aa("script",{src:this.config.url+"/morpheus_console.js"}).then(function(){var b=n.a.sbi_km.logData;a.xb().forEach(function(d){a.D(b[d.id].service,d.ib,b[d.id].template,d.Ib)})}).catch(function(b){a.F((new Date).toLocaleString(),"error in debug output",b)})};
c.a=a},function(l,c){c.a=function(c){(function(a){var c=Date.now();"performance"in a||(a.performance={});"timing"in a.performance?a.performance.timing.navigationStart&&(c=a.performance.timing.navigationStart):a.performance.timing={navigationStart:c};"now"in a.performance||(a.performance.now=function(){return Date.now()-c})})(c);Object.assign||Object.defineProperty(Object,"assign",{enumerable:!1,configurable:!0,writable:!0,value:function(a){if(void 0===a||null===a)throw new TypeError("Cannot convert first argument to object");
for(var c=Object(a),b=1;b<arguments.length;b++){var e=arguments[b];if(void 0!==e&&null!==e)for(var p=Object.keys(Object(e)),g=0,d=p.length;g<d;g++){var f=p[g],q=Object.getOwnPropertyDescriptor(e,f);q&&q.enumerable&&(c[f]=e[f])}}return c}})}},function(l,c,e){function a(a,c,e,l){var f=this;this.eb=function(a,d,c,q){var t=Date.now(),r=Object.assign({},f.da.ea),e=r[Object.keys(r).find(function(a){a=r[a];return a.id===d&&!a.ma})];if(!e)return Promise.reject("Could not find winning bid");var u=f.C[e.K];
if(!u)return Promise.reject("Could not find a slot for the winning bid");u.Gb[e.id]=t;return f.D.eb(u,a,e.qa,c,q,e.size).then(function(a){var b=Object.keys(a.Gb);b=f.da.ea[b[0]];f.G.log("sbi",g.B,[b.I,b.P]);b.ma=!0;e.db=3;f.Y.oa([b]);a.kb=null}).catch(function(a){b.a.console.log(a);f.G.log("sbi",g.u,[a])})};this.oc=function(){var a={Wa:!1};if("object"!==typeof a)return f.C;a.$a=!1;return Object.keys(f.C).reduce(function(b,d){var c=f.C[d],g;for(g in a)if(c[g]!==a[g])return b;b[d]=c;return b},{})};
this.hc=function(a){if("object"===typeof a)return a.$a=!1,f.C[Object.keys(f.C).find(function(b){b=f.C[b];for(var d in a)if(b[d]!==a[d])return!1;return!0})]};this.Jc=function(a){f.H=a};this.J=function(a){var b={};a=L(a);for(var d=a.next();!d.done;d=a.next()){d=f.D.Ea(d.value);var c=null,g;for(g in f.C)if(f.C[g].O===d){c=f.C[g].id;break}null!=c&&(b[c]=f.C[c])}return b};this.F=function(a){var b={},d={};a.forEach(function(a){var c=f.D.Ea(a),g=f.D.yb(a);if(!(c in d)){b[g]=b[g]++||1;var e=Object(h.j)();
d[e]={K:g,xd:g+":"+b[g],fc:"google_ads_iframe_"+a.getSlotId().getId(),O:c,id:e,vd:!1,nd:!1,$a:!1,Gb:{},ea:[],kb:null,na:f.D.vb(a),Ja:{},md:f.D.kc(a),Ga:f.D.vb.bind(f.D,a),Wa:!1,rb:!1,Pc:0,tc:n}}});f.C=Object.assign(f.C,d)};this.Hc=function(a){for(var b in a)if(b in f.C){var d=f.C[b].O;f.C[b].kb=a[b];f.C[b].Ja=a[b].targeting;var c=Object.assign({},f.da.ea)[a[b].id];c&&(c.qa=a[b].creative,c.size=a[b].size,c.Ja=a[b].targeting,f.C[b].Ja.sbi_size=a[b].size,f.D.Gc(d,a[b].targeting))}};var q=this;this.G=
a;this.config=c;this.C={};this.da=e;this.Y=l;this.D=new p.a(this.G,this);b.a.sbi_km.API.render=this.eb;d.a.$("initialized",function(a,b){q.G.log("sbi",g.n,[a]);q.F(a);"function"===typeof b&&b();d.a.T("slotsDefined",function(a){q.G.log("sbi",g.y,[a]);q.F(a)})});d.a.T("slotsDestroyed",function(a){a.forEach(function(a){var b=q.D.Ea(a);a=q.D.yb(a);for(var d in q.C)q.C[d].O===b&&q.C[d].K===a&&(q.C[d].$a=!0,q.G.log("sbi",g.z,[q.C[d]]))},this)});d.a.T("slotsRequestingRender",function(a){var b=q.J(a.R);q.H(b,
a.done)})}function n(a){a=void 0===a?this:a;if(-1<a.O.indexOf(" ")||1>a.na.length)return!1;var b=/^([a-zA-Z0-9\/_.*\\!<:()-]+)$/;return a.K&&b.test(a.K)?!0:!1}var b=e(0),h=e(1),p=e(13),g=e(2),d=e(4);a.prototype.H=function(){};z.Object.defineProperties(a.prototype,{R:{configurable:!0,enumerable:!0,get:function(){return this.C},set:function(a){this.C=a}}});c.a=a},function(l,c,e){function a(a,f){this.D=!1;var d=this;this.D=!1;this.H=this.va=Function;this.wa={};this.C={};this.G=a;this.J=[];this.pa=f;
b.a.googletag=b.a.googletag||{};b.a.googletag.cmd=b.a.googletag.cmd||[];if(b.a.googletag.pubadsReady)a.log("sbi",g.r);else{a=this.Rb();var c=!1;b.a.googletag.cmd[a](function(){c||(c=!0,d.wa=b.a.googletag,d.C=d.wa.pubads(),d.Vb(),d.Ub())});!1!==Object(p.l)(f.config,"globalSettings.osEnabled")&&n(a,b.a.googletag.cmd);this.L={kd:!1,Ua:!1,sb:!1};this.U={}}}function n(a,f){f=void 0===f?b.a.googletag.cmd:f;if("u"===a[0]){var d=f.splice;f[a]=function(a){d.apply(f,[1,0,a]);return this.length};f.splice=function(){var a=
f.shift();d.apply(f,arguments);return d.apply(f,[0,0,a])}}}var b=e(0),h=e(4),p=e(1),g=e(2);a.prototype.Rb=function(){return null!=b.a.googletag.cmd.length?"unshift":"push"};a.prototype.Xb=function(a,b,c){c?a.postMessage({creative:b,message:"SBI_RENDER"},c):a.document.write(b)};a.prototype.Yb=function(a,f,c,e,h,p,x){e=e.split("x");var d=parseInt(e[0],10),q=parseInt(e[1],10);if(this.Qb(a,d,q))if(p)Array.from(b.a.document.getElementById(f).getElementsByTagName("div")).filter(function(a){return-1<a.id.indexOf("google_ads_iframe")}).forEach(function(a){var b=
a.childNodes[0];b.width=d.toString();b.height=q.toString();a.style.width=d+"px";a.style.height=q+"px";c.postMessage({creative:h,message:"SBI_RENDER"},p)});else{if(c.inDapIF)try{var u=b.a.document.getElementsByName(c.frameElement.name)[0];u.width=d.toString();u.height=q.toString()}catch(D){this.G.log("sbi",g.k)}c.document.write(h)}else x(a)};a.prototype.Wb=function(a){var b=this;return function(d){var f=b.F(a.O);b.ba(f);b.H.apply(b.C,[[f],{changeCorrelator:!1}]);throw d;}};a.prototype.eb=function(a,
b,c,e,h,p){var d=this,f=this;return(new Promise(function(q,u){f.G.log("sbi",g.v,[a]);a.rendering=!0;var t=c;e&&Object.keys(e).forEach(function(a){Array.isArray(e[a])||(e[a]=[e[a]]);t=t.replace("%%"+a+"%%",e[a].join(","))});if(d.pa.config.globalSettings.supportResizing){var r=d.F(a.O);d.Yb(r,a.O,b,p,t,h,u)}else d.Xb(b,t,h);f.G.log("sbi",g.t,[a]);q(a)})).catch(this.Wb(a))};a.prototype.ba=function(a){var b=a.getTargetingMap();b=Object.keys(b).filter(function(a){return"sbi"===a.substr(0,3)});0<b.length&&
b.forEach(function(b){a.clearTargeting(b)})};a.prototype.F=function(a){var b=this;return this.ca().find(function(d){return b.Ea(d)===a})||null};a.prototype.Ea=function(a){return a&&"getSlotElementId"in a?a.getSlotElementId():null};a.prototype.ca=function(){return this.C.getSlots()};a.prototype.yb=function(a){return a.getAdUnitPath()};a.prototype.Qb=function(a,b,c){var d=!1;this.Ga(a).forEach(function(a){d=d||a.Ob===b&&a.Ab===c});return d};a.prototype.vb=function(a){return this.Ga(a).map(function(a){return a.Ob+
"x"+a.Ab})};a.prototype.Ga=function(a){a=a.getSizes.apply(a,Object(p.k)());a=Array.isArray(a)?a:[];return a.filter(function(a){return"function"===typeof a.getWidth}).map(function(a){return{Ob:a.getWidth(),Ab:a.getHeight()}})};a.prototype.Gc=function(a,b){if(a=this.F(a))for(var d in b)d&&b[d]&&a.setTargeting(d,b[d])};a.prototype.Vb=function(){var a=this,f=b.a.googletag.enableServices;b.a.googletag.enableServices=function(){var d=this,c=arguments;a.G.log("sbi",g.h);a.D||(a.D=!0,h.a.fa("initialized",
a.ca(),function(){f.apply(d,c);a.G.log("sbi",g.l,[a.J.toString()]);a.J.forEach(function(a){return b.a.googletag.display(a)});a.J=[]}))};var c=this.C.enableSingleRequest;this.C.enableSingleRequest=function(){a.D||(a.L.sb=!0);c.apply(this,arguments)};var e=this.C.disableInitialLoad;this.C.disableInitialLoad();a.Ua=e;this.C.disableInitialLoad=function(){a.Sb||(a.L.Ua=!0);e.apply(this,arguments)}};a.prototype.Ub=function(){function a(a){if(a&&Object.keys(a).length){var b=Object(p.j)();c.U[b]={};for(var d in a)a[d].Wa=
!0;c.U[b]=a;d=Object.keys(a).map(function(b){return c.F(a[b].O)});for(var f=L(d),r=f.next();!r.done;r=f.next())c.ba(r.value);var q={R:d,done:function(){var a=e.U[b],d=Object.keys(a).map(function(b){return e.F(a[b].O)});e.G.log("sbi",g.s,[q.R]);e.H.apply(e.C,[d,{changeCorrelator:!1}])}};h.a.fa("slotsRequestingRender",q)}}function f(a){c.va.apply(b.a.googletag,a)}var c=this,e=this,n=b.a.googletag.defineSlot;b.a.googletag.defineSlot=b.a.googletag.defineUnit=function(){"/"!==arguments[0].charAt(0)&&(arguments[0]=
"/"+arguments[0]);var a=n.apply(this,arguments);if(a){var b=a.getAdUnitPath;a.getAdUnitPath=function(a){a=b.call(this,a);return("/"!==a.charAt(0)?"/":"")+a};e.D&&h.a.fa("slotsDefined",[a])}return a};var w=b.a.googletag.defineOutOfPageSlot;b.a.googletag.defineOutOfPageSlot=function(){"/"!==arguments[0].charAt(0)&&(arguments[0]="/"+arguments[0]);var a=w.apply(this,arguments);if(a){var b=a.getAdUnitPath;a.getAdUnitPath=function(a){a=b.call(this,a);return("/"!==a.charAt(0)?"/":"")+a};a.isOutOfPage=!0;
e.D&&h.a.fa("slotsDefined",[a])}return a};var x=b.a.googletag.destroySlots;b.a.googletag.destroySlots=function(){var a=x.apply(this,arguments);if(a){var b=arguments.length?arguments[0].filter(function(a){return e.Tb(a)}):e.C.getSlots();h.a.fa("slotsDestroyed",b)}return a};this.H=this.C.refresh;this.C.refresh=function(){var a=Array.from(arguments),b={};0<a.length&&Array.isArray(a[0])?0===a[0].length?b.R=[]:(b.R=[],a[0].forEach(function(a){a&&"object"===typeof a&&"function"===typeof a.getSizes?b.R.push(a):
e.G.log("sbi",g.p,[a])})):b.R=e.ca();b.done=function(){e.G.log("sbi",g.s,[b.R]);e.H.apply(e.C,a)};b.R.forEach(function(a){e.ba(a)});h.a.fa("slotsRequestingRender",b)};this.va=b.a.googletag.display;b.a.googletag.display=function(b){for(var d=[],e=0;e<arguments.length;++e)d[e-0]=arguments[e];c.Sb=!0;e=0<d.length&&("string"===typeof d[0]||"object"===typeof d[0]);var h=d[0];"object"===typeof h&&(h=h.id);h=c.pa.hc({O:h||""});var p=c.pa.oc(),q=!!h,u=c.L.Ua,r=c.L.sb,w=q&&!0===h.rb;c.D?q&&e?w||(h.rb=!0,f(d),
u||(r?a(p):(d=h,d.Wa=!0,c.G.log("sbi",g.i,[d]),d=c.F(d.O),c.C.refresh([d],{changeCorrelator:!1})))):f(d):(c.G.log("sbi",g.j,[d[0]]),c.J.push(d[0]))}};a.prototype.kc=function(a){return a.hasOwnProperty("isOutOfPage")&&a.isOutOfPage};a.prototype.Tb=function(a){try{return"function"===typeof a.cd}catch(f){return!1}};c.a=a},function(l,c,e){function a(a,c,e){var f=this;this.rc=function(a){a.adapterSettings.forEach(function(c){var e=c.name;c=new b.a(a,e);var g=d.a[e];c.Ba&&(f.C[e]={ja:g,N:c},f.G.log("sbi",
p.e,[e]),f.C[e].Ic=g.ua(c,f.Y,f.G).then(function(a){f.G.log("sbi",p.f,[e]);return a}))})};this.L=function(a){var b={};Object.keys(a).forEach(function(d){a[d].forEach(function(a){b[a.id]=a})});f.D=Object.assign(f.D,b);return b};this.Jb=function(a,b,d,c){f.G.log("sbi",p.x,[b]);f.G.log("sbi",p.w);var e=Object.keys(f.C).map(function(a){return{da:f.C[a],Ka:!1}});f.F[d]=new g.a(d,e,a,b,f.G,f.Y);f.F[d].ua(function(a){c(f.L(a))})};this.J=function(a,b){var d=a.reduce(function(a,b){a[b.P]=a[b.P]||[];a[b.P].push(b);
return a},{});return Object.keys(d).reduce(function(a,c){var e=n.a.sonobiDealWinsOverHighestCPM(d[c],f.G);e&&(a["sbi_"+c+"_price"]=Object(n.b)(e.I,b),a["sbi_"+c+"_size"]=e.size);return a},{})};this.pc=function(a,b,d){if(0===a.length)return{};a=Object(n.d)(a);for(var c={},e=L(Object.keys(a)),g=e.next();!g.done;g=e.next())if(g=g.value,0!==a[g].length){var q=n.a.sonobiDealWinsOverHighestCPM(a[g],f.G);if(null!=q){q.lb=!0;c[g]={targeting:{}};c[g].id=q.id;f.H.X.ga().widgetRender&&(c[g].targeting.sbi_lookup_id=
h.a.sbi_km.id);c[g].targeting.sbi_kmid=q.id;c[g].targeting.sbi_bidder=q.P;c[g].targeting.sbi_ct=q.jb;var u=Object(n.b)(q.I,b);"number"===typeof u&&0<u&&(c[g].targeting.sbi_price=u);for(var l in q.Va)c[g].targeting[l]=q.Va[l];u=q.qa;u=Object(n.n)(u,q.Cb,"%%");c[g].creative=u;c[g].size=q.size;d&&(c[g].targeting=Object.assign(c[g].targeting,f.J(a[g],b)))}}f.G.log("sbi",p.A,[c]);return c};this.G=a;this.D={};this.Y=c;this.C={};this.H=e;this.F={}}var n=e(1),b=e(15),h=e(0),p=e(2),g=e(16),d=e(17);z.Object.defineProperties(a.prototype,
{ea:{configurable:!0,enumerable:!0,get:function(){return this.D},set:function(a){this.D=a}}});c.a=a},function(l,c,e){function a(a,c){var d=this;this.J=b;this.H=h;this.Ya=function(a){var b=a.bb;a=d.D[void 0===a.M?d.M:a.M];b&&(a=a[b],a=g.e.ab(b)&&!a?d.aa.sa(g.e.Da(d.aa.sa()),b):a);return a};if(!c)throw Error("Provide an adapter name in your AdapterSettingsConfigInterface constructor.");this.S=a.adapterSettings;this.aa=new p.a(a);this.D=n(this.S);this.M=c;this.C=this.D[c]}function n(a){for(var b={},
d=0;d<a.length;d++)b[a[d].name]=a[d];return b}function b(a,b,c){a=g.e.ha(a,void 0===c?"dimensions.platforms":c)||[];return"*"===b||0===a.length||-1<a.indexOf("*")?!0:-1<a.indexOf(b)}function h(a,b){b=void 0===b?"dimensions.domains":b;var d=g.e.Q().location;a=g.e.ha(a,b)||[];if(0===a.length||-1<a.indexOf("*"))return!0;if("string"===typeof a)return(new RegExp(a)).test(d);for(b=0;b<a.length;b++)if((new RegExp(a[b])).test(d))return!0;return!1}var p=e(6),g=e(1);a.prototype.Fa=function(a){var b=a.name;
return this.F({M:void 0===a.M?this.M:a.M,V:void 0===a.V?"requestSettings":a.V}).find(function(a){return a.name===b})};a.prototype.nc=function(){return(this.Z({name:"protocol"})||"https").replace(":","").replace("//","")};a.prototype.Z=function(a){return(a=this.Fa({name:a.name,V:void 0===a.V?"requestSettings":a.V,M:void 0===a.M?this.M:a.M}))?a.value:void 0};a.prototype.F=function(a){var d=[];a=this.D[void 0===a.M?this.M:a.M][void 0===a.V?"requestSettings":a.V]||[];for(var c=0;c<a.length;c++){var e=
a[c];if(e.hasOwnProperty("dimensions")){var p="*";this.aa.S&&(p=g.e.Da(this.aa.sa()));h(e)&&b(e,p)&&d.push(e)}else d.push(e)}return d};a.prototype.xc=function(a){var b=a.K,d=void 0===a.Bb?"placementid":a.Bb;a=this.F({M:void 0===a.M?this.M:a.M,V:void 0===a.V?"requestSettings":a.V});for(var c=b;0<=c.lastIndexOf("/")&&"/"!==c;){b=a.filter(function(a){return a.name.toLowerCase()===d.toLowerCase()});b=L(b);for(var e=b.next();!e.done;e=b.next())if(e=e.value,(g.e.ha(e,"dimensions.adUnits")||[]).some(function(a){return a.toLowerCase()===
c.toLowerCase()}))return[e];c=c.substr(0,c.lastIndexOf("/"))}return[]};z.Object.defineProperties(a.prototype,{Ba:{configurable:!0,enumerable:!0,get:function(){var a="false"===g.e.mc("sbi_"+this.M)?!1:!0,b="*";this.aa.S&&(b=g.e.Da(this.aa.sa()));var c=1;"number"===typeof this.C.frequency&&(c=this.C.frequency);return a&&!this.C.disabled&&this.J(this.C,b,"platforms")&&this.H(this.C,"domain")&&Math.random()<=c}}});c.a=a},function(l,c,e){function a(a,b,c,e,h,u){this.id=a;this.D=Object(n.c)(b);this.R=c;
this.G=h;this.Y=u;this.ea=[];this.H=e;this.Ha=!1;this.ua=this.ua.bind(this);this.C=this.C.bind(this)}var n=e(1),b=e(0),h=e(2);a.prototype.C=function(){return this.ea.reduce(function(a,b){(a[b.K]=a[b.K]||[]).push(b);return a},{})};a.prototype.F=function(c,e,d){var f=this;return function(g){for(var h=[],p=0;p<arguments.length;++p)h[p-0]=arguments[p];h.forEach(function(g){g.db=2;e&&(g.I=Object(n.b)(g.I,e));g.Ia=Math.round(b.a.performance.now()-d);g.ma=!1;g=a.F(Object(n.i)("sbi_price_"+c.da.ja.name),
g);f.Ha?(g.Ha=!0,f.Y.oa([g])):c.Ka?(g.bc=!0,f.Y.oa([g])):f.ea.push(g)})}};a.prototype.ua=function(c){var e=this,d=Object(n.m)(function(){c(e.C())});b.a.setTimeout(function(){e.G.log("sbi",h.m);e.Ha=!0;d()},this.H);var f=0;this.D.forEach(function(c){var g=c.da,p=g.ja.N.Ya({bb:"timeout"}),q=g.ja.N.Ya({bb:"priceRules"}),l=Object(n.m)(function(){f+=1;f>=e.D.length&&d()});b.a.setTimeout(function(){e.G.log("sbi",h.d,[g.ja.name,p]);c.Ka=!0;l()},p);var r=b.a.performance.now(),k=a.C(g.ja.N,e.R);0<Object.keys(k).length?
g.Ic.then(function(){g.ja.fb(k,e.id,e.F(c,q,r),l)}).catch(function(){l()}):l()})};c.a=a;a.D=function(a){return Object.keys(a).reduce(function(b,c){var d=a[c];d.tc()&&(b[c]=d);return b},{})};a.C=function(b,c){b=b.Ya({bb:"sizes"});var d={},e;for(e in c)c.hasOwnProperty(e)&&(d[e]=Object.assign({},c[e]),d[e].na=Object(n.f)(c[e].Ga(),b));return a.D(d)};a.F=function(a,b){a&&""!==b.qa&&0<b.I&&(b.I=parseInt(a,10));return b}},function(l,c,e){l=e(18);e=e(19);c.a={sonobi:new l.a(e.a)}},function(l,c,e){function a(a){this.caller=
n.a;this.name=a.name;this.Ta=a.Ta;this.hb=a.hb;this.fb=a.fb;this.parse=a.parse;this.Ca=a.Ca;this.Xa=a.Xa;this.done=Function;this.caller=n.a;this.N=null;this.G={};this.D=Promise.resolve({});this.Pb=a.Pb;this.C=!1}var n=e(3),b=e(2);a.prototype.ua=function(a,c,e){this.C||(this.G=e,this.N=a,this.C=!0,e.log("sbi",b.e,[this.name]),this.D=this.hb(a,c,e)||Promise.resolve({}));return this.D};c.a=a;a.Ca=function(a){return a}},function(l,c,e){function a(a){switch(a){case "href":return g.e.Q().location;case "hash":return g.e.Q().protocol+
g.e.Q().host+g.e.Q().pathname+g.e.Q().la;case "search":return g.e.Q().protocol+g.e.Q().host+g.e.Q().pathname+g.e.Q().search;case "pathname":return g.e.Q().protocol+g.e.Q().host+g.e.Q().pathname}}function n(a){var c=["hfa","cdf","ant","gmgt"].map(function(c){return b(a,c)}).filter(function(a){return a});c.push(h(a));return c.reduce(function(a,b){var c=b.gb;b=b.exec;var d="";"function"===typeof b&&(d=b(c));if(!d)return a;if("object"===typeof d||Array.isArray(d))d=JSON.stringify(d);return a+"&"+c.name.replace("_cookie_key",
"")+"="+encodeURIComponent(d)},"")}function b(a,b){var c=a.Fa({name:b});if(c)return{gb:c,exec:function(a){return g.e.ha(d.a,a.value)}};if(c=a.Fa({name:""+b+"_cookie_key"}))return{gb:c,exec:function(a){return g.e.zb(a.value)}}}function h(a){return{gb:{name:"vp"},exec:function(){return(g.e.Da(a.aa.sa())||"desktop").toLowerCase()}}}function p(a,b){b=void 0===b?"href":b;return a.Z({name:"referrer"})||g.e.Q()[b]}var g=e(1),d=e(0),f=e(20),q=e(2),u=e(21),k=e(22);c.a={hb:function(b,c,d){this.N=b;this.Y=c;
this.G=d;this.location=a(b.Z({name:"pageViewLocation"}));this.Eb=g.e.ub();this.ta=new u.a(b);this.ta.gc();this.Nb=new k.a(b)},fb:function(b,c,e,h){function l(){return Promise.resolve()}var k=this,u={},r={},m={slots:{}},t=a(this.N.Z({name:"pageViewLocation"}));t!==this.location&&(this.location=t,this.Eb=g.e.ub());var x=!1;for(A in b)if(null!=b[A]&&Object.keys(b[A]).length){t=b[A];var w=t.K+"|"+encodeURIComponent(t.O);x=this.N.xc({K:b[A].K,Bb:"slot_override"})||[];if(0<x.length){var C=g.e.sc(g.e.ha(x[0],
"dimensions.sizes"),t.na);if(0<C.length)x=this.ta.wb({sbi_ad:t.K,sbi_size:C}),u[w]=C.join(",");else continue}else x=this.ta.wb({sbi_ad:t.K,sbi_size:t.na}),u[w]=t.na.join(",");x&&(m.slots[w]=x,delete u[w]);r[w]=new f.a(t.na[0],"sonobi","sonobi",A,t.K,this.Y,c)}c=n(this.N);var A=this.N.Z({name:"testUrl1"});t=this.N.nc();A=A||t+"://apex.go.sonobi.com/trinity.json?key_maker=";var M=g.e.Za(),N=this.Xa(A,u,c,this.Eb,p(this.N,"hostname"),this.Nb.value);N+=this.ta.Ba?"&or=1":"";this.G.log("sbi",q.c,["sonobi",
b]);c=this.N.Fa({name:"pubid"});null!=c&&null==g.e.zb("sbi_user_sync_complete")&&(l=this.caller.Aa.bind(this.caller,"script",{src:"https://sync.go.sonobi.com/uc.js?pubid="+c.value}),c=new Date,c.setTime(Number(c)+12096E5),d.a.document.cookie="sbi_user_sync_complete=true; expires="+c.toUTCString()+"; path=/");this.G.log("sbi",q.c,["sonobi",b]);return l().then(function(){return Object.keys(u).length?k.caller.Sa(N,null,{withCredentials:!0}):"{}"}).then(JSON.parse).then(function(a){a.slots?Object.assign(a.slots,
m.slots):(m.sbi_dc=k.ta.Mb,a=m);a.sbi_px&&a.sbi_px.forEach(function(a){k.caller.Aa("image",{src:a.url})});k.G.log("sbi",q.b,["sonobi",b,a]);var c=g.e.lc(M);a=k.parse.call(k,a,b,c,r);e.apply(null,[].concat(P(a)));h();return a})},parse:function(a,b,c,d){var e=[];if(a.slots)for(var f in b)if(null!=b[f]&&Object.keys(b[f]).length){var g=b[f],h=g.K+"|"+g.O,l=g.K+"|"+encodeURIComponent(g.O);if(h in a.slots){l=d[l];h=a.slots[h];"sbi_aid"in h||(h={sbi_aid:null,sbi_apoc:null,sbi_size:null});"sbi_dozer"in h||
(h.sbi_dozer=!1);"sbi_pri"in h||(h.sbi_pri=10);"sbi_mouse"in h||(h.sbi_mouse=0,h.sbi_pri=1);l.I=100*parseFloat(h.sbi_mouse);l.size=h.sbi_size||l.size;l.W=h.sbi_dozer;l.jb=h.sbi_ct||l.jb;l.ka=parseInt(h.sbi_pri,10);l.yc=c;l.Cb={sbi_aid:h.sbi_aid,sbi_dc:a.sbi_dc};var k=this.N.Z({name:"testUrl2"})||"//%%sbi_dc%%apex.go.sonobi.com/sbi.js";l.qa=this.Ca(k+"?ref="+encodeURIComponent(p(this.N))+"&aid=%%sbi_aid%%&as=null","SCRIPT");l.Zb=g.K;h.sbi_dozer&&(l.Va={sbi_dozer:h.sbi_dozer});e.push(l)}"sbi_suid"in
a&&(this.Nb.value=a.sbi_suid)}this.G.log("sbi",q.a,["sonobi",b,e]);return e},name:"sonobi",Ta:"sonobi",Zc:b,yd:"https://sync.go.sonobi.com/uc.js",Vc:a,Ca:g.e.dc,Xa:function(a,b,c,e,f,g){b=encodeURIComponent(JSON.stringify(b));f=encodeURIComponent(f);return""+a+b+c+"&pv="+e+"&ref="+f+(!1===g?"":"&suid="+g)+"&lib_name=3pdm&lib_v="+d.a.sbi_km.version}}},function(l,c,e){function a(a,c,e,g,d,f,l){this.mb=k.e.Za();this.J=g;this.La=d;this.Pa=0;this.Ma=e;this.nb=c;this.D="";this.Ra=a;this.ya={};this.Na="";
this.F=10;this.C=-1;this.Qa=1;this.H={};this.Oa=l;this.xa=0;this.L="display";this.ma=!1;this.db=1;"function"===typeof f.oa&&f.oa([this])}var k=e(1);a.prototype.ob=function(){return Object.assign(Object.create(this),this)};a.prototype.ic=function(){var a=this.ob(),c={buyerid:a.Ma,buyername:a.nb,adunit_code:a.La,pageViewId:a.Oa,bidid:a.mb,p:a.db,response:a.Qa,s:a.Ra||"0x0",bid:a.Pa,latency:a.wc,jsLatency:a.xa,auctionid:k.e.ha(a.ya,"sbi_aid"),datacenter:k.e.ha(a.ya,"sbi_dc")};a.W&&"string"===typeof a.W&&
(c.dealid=a.Na);return c};z.Object.defineProperties(a.prototype,{id:{configurable:!0,enumerable:!0,get:function(){return this.mb}},U:{configurable:!0,enumerable:!0,get:function(){return this.Oa},set:function(a){this.Oa=a}},K:{configurable:!0,enumerable:!0,get:function(){return this.J},set:function(a){this.J=a}},jb:{configurable:!0,enumerable:!0,get:function(){return this.L},set:function(a){this.L=a}},Zb:{configurable:!0,enumerable:!0,get:function(){return this.La},set:function(a){this.La=a}},I:{configurable:!0,
enumerable:!0,get:function(){return this.Pa},set:function(a){this.Pa=a}},P:{configurable:!0,enumerable:!0,get:function(){return this.nb}},Cb:{configurable:!0,enumerable:!0,get:function(){return this.ya},set:function(a){this.ya=a}},wc:{configurable:!0,enumerable:!0,get:function(){return 0>=this.Ia||!this.Ia?-1:this.Ia},set:function(a){this.xa=Math.round(a)}},yc:{configurable:!0,enumerable:!0,get:function(){return 0>=this.C||!this.C?-1:Math.round(this.C)},set:function(a){this.C=Math.round(a)}},Ia:{configurable:!0,
enumerable:!0,get:function(){return Math.round(this.xa)},set:function(a){this.xa=Math.round(a)}},size:{configurable:!0,enumerable:!0,get:function(){return this.Ra},set:function(a){this.Ra=Array.isArray(a)?a.join("x"):a}},Ta:{configurable:!0,enumerable:!0,get:function(){return this.Ma},set:function(a){this.Ma=a}},qa:{configurable:!0,enumerable:!0,get:function(){return this.D},set:function(a){this.D=a}},W:{configurable:!0,enumerable:!0,get:function(){return this.Na},set:function(a){this.Na=a}},ka:{configurable:!0,
enumerable:!0,get:function(){return this.F},set:function(a){this.F=a}},Ec:{configurable:!0,enumerable:!0,get:function(){return this.Qa},set:function(a){this.Qa=a}},Va:{configurable:!0,enumerable:!0,get:function(){return this.H},set:function(a){this.H=a}}});c.a=a},function(l,c,e){function a(a){this.C=[];this.Mb="mco-1-";this.config=a;this.Ba=Number(this.config.Z({name:"oracle"})||0);this.F="https://apex.go.sonobi.com/oracle.json"}var k=e(3);a.prototype.wb=function(a){var b=this;return this.C.find(function(c,
e){for(var d=0,f=Object.keys(a);d<f.length;d++)if(void 0===c[f[d]]||c[f[d]]!==a[f[d]]&&!a[f[d]].includes(c[f[d]]))return!1;b.C.splice(e,1);return!0})};a.prototype.gc=function(){var a=this;this.Ba?k.a.Sa(this.F,void 0,{withCredentials:!0}).then(function(b){return(b=JSON.parse(b+""))&&Object.keys(b.slots).length?(a.Mb=b.sbi_dc,a.D(b)):{}}):Promise.resolve({})};a.prototype.D=function(a){var b=Object.keys(a.slots).map(function(b){var c=a.slots[b];b=b.split("|");c.sbi_ad=b[0];return c});return this.C=
[].concat(P(b))};c.a=a},function(l,c,e){function a(a){this.C=a.Z({name:"suidStorageStrategy"});this.D=!k.a.cb;this.L()}var k=e(0);a.prototype.J=function(a,c){var b=new Date,e=b.getTime();c*=6E4;b.setTime(c+e);b=b.toGMTString();a={value:a,expiryTimeMS:c+e};e=JSON.stringify(a);k.a.document.cookie="suid="+e+"; Expires="+b+"; Path=/";return a};a.prototype.F=function(){var a={},c=k.a.decodeURIComponent(k.a.document.cookie).split(";");c=L(c);for(var e=c.next();!e.done;e=c.next())if(e=e.value,0===e.trim().indexOf("suid=")){e=
L(e.trim().split("="));c=e.next().value;e=e.next().value;a[c]=e;break}return"suid"in a?JSON.parse(a.suid):!1};a.prototype.ca=function(a){a={value:a,expiryTimeMS:12096E5+Date.now()};k.a.cb.wd("suid",JSON.stringify(a));return a};a.prototype.H=function(){var a=JSON.parse(k.a.cb.gd("suid"));return a?a:!1};a.prototype.L=function(){var a=this.F();a&&a.expiryTimeMS<Date.now()&&this.U();this.D||(a=this.H())&&a.expiryTimeMS<Date.now()&&this.ba()};a.prototype.U=function(){this.J("",-20160)};a.prototype.ba=
function(){k.a.cb.rd("suid")};z.Object.defineProperties(a.prototype,{value:{configurable:!0,enumerable:!0,get:function(){if("c"===this.C){var a=this.F();if(a)return a.value}else if("ls"===this.C){if(this.D)return!1;if(a=this.H())return a.value}return!1},set:function(a){if("c"===this.C)return this.J(a,20160);if("ls"===this.C)return this.D?void 0:this.ca(a)}}});c.a=a},function(l,c,e){function a(a,b){this.C=[];this.caller=k.a;this.G=a;this.D=b}var k=e(3),b=e(1),h=e(2),p=e(0),g=e(4),d={1:"BidRequested",
2:"BidReceived",3:"BidRendered"},f=["audienceNetwork"];a.prototype.F=function(a){var b=this;this.C.length||p.a.setTimeout(function(){b.J(b.C);b.C=[]},100);this.C.push(a)};a.prototype.H=function(a){var b=0;a.ac&&(b|=16);a.Ka&&(b|=8);a.lb&&(b|=4);a.ma&&(b|=2);switch(b){case 0:return 1;case 8:return 0;case 16:return 9;case 20:return 4;case 24:return 2;case 22:return 6;default:throw Error("Invalid bid status: "+b.toString(2)||"Assertion failed!");}};a.prototype.oa=function(a){a=L(a);for(var b=a.next();!b.done;b=
a.next()){b=b.value;this.G.log("sbi",h.g,[b.P,b]);var c={ac:0<b.I||b.W,Ka:b.Ha||b.bc,lb:b.lb,ma:b.ma},d=void 0;try{d=this.H(c),b.Ec=d}catch(x){this.G.log(h.o,[x.message])}this.F(b.ic())}};a.prototype.L=function(a){var c=b.e.uc(a,"buyername bid adunit_code s jsLatency bidid".split(" "));-1===f.indexOf(c.buyername)&&g.b.fa(d[a.p],c)};a.prototype.J=function(a){var c=void 0,d=this;c=void 0===c?this.D.$b.jc():c;a.forEach(function(a){return d.L(a)});if(c){var e=b.e.qc(a,"pageViewId");Object.keys(e).forEach(function(a){var f=
e[a].map(function(a){return b.e.zc(a,["pageViewId"])});a=c+"?pageviewid="+a+"&corscred=1&ver="+p.a.sbi_km.version;f=JSON.stringify(f);return d.caller.Sa(a,f,{Db:"POST"}).catch(function(){})})}};c.a=a},function(l,c,e){var a=e(25),k=e(5),b=e(6);c.a=function(c){this.S=c;this.$b=new a.a(c);this.X=new k.a(c);this.aa=new b.a(c)}},function(l,c,e){function a(a){this.S=a.analyticsSettings;this.X=new k.a(a)}var k=e(5),b=e(1);a.prototype.jc=function(){var a=this.S.url;b.e.ab("url")&&!a&&(a=this.X.ga("url"));
return a};c.a=a},function(l,c,e){c.a=function(b,c,e,g,d,f){function h(){r=Object(a.j)();n[r]={qb:0,tb:0,Hb:[],Lb:[],Kb:[],Fb:!0};k.a.setTimeout(function(){n[r].Kb.forEach(function(a){return a()});n[r].Fb=!1},c.globalSettings.renderQueue)}function l(a){r&&n[r].Fb||h();n[r].Kb.push(a);n[r].qb++}function p(a,b){var c=n[a].Hb.push(b)-1;return function(b){n[a].tb++;n[a].Lb[c]=b;n[a].tb===n[a].qb&&m(a)}}function m(a){n[a].Hb.forEach(function(b,c){b(n[a].Lb[c])})}var n={},r;return{Dc:function(h,n){k.a.sbi_morpheus.initialized||
k.a.sbi_morpheus.initialize();if(Object.keys(h).length){var q=Object(a.j)(),m=Object(a.m)(function(a){var c=Object.keys(a).map(function(b){return a[b]});c.length?(g.Hc(b.pc(c,d.X.ga("priceRules")||[],d.X.ga("sendAllKeys")||!1)),c=c.map(function(a){return a.ob()}),c.length&&(c=c.map(function(a){a.K=h[a.K].K;return a}),f.oa(c),n())):n()});0<c.globalSettings.renderQueue?l(function(){return b.Jb(h,e,q,p(r,m))}):b.Jb(h,e,q,m)}},ld:h,Xc:l,$c:p,qd:m,td:n,sd:r}};var a=e(1),k=e(0)},function(l,c,e){var a=e(0),
k=e(4);c.a=function(){var b=a.a.sbi_morpheus&&a.a.sbi_morpheus.cmd?a.a.sbi_morpheus.cmd:[],c=Object.assign(a.a.sbi_morpheus||{},{registration:{},register:function(){},enableReactiveSizes:function(){},callOperator:function(){},initialized:!1,initialize:function(){for(;0<b.length;)try{b.shift()()}catch(p){}c.initialized=!0},cmd:function(){var b=[],c=b.push;b.push=function(d){for(var e=[],g=0;g<arguments.length;++g)e[g-0]=arguments[g];return a.a.sbi_morpheus.initialized?e.reduce(function(a,b){try{b()}catch(w){}a++;
return a},0):c.apply(b,e)};return b}(),addEventListener:function(a,b){return k.b.T(a,b)},removeEventListener:function(a,b){return k.b.Cc(a,b)}});return c}},function(k,c,e){function a(a,c,e){var d=this;this.F=l;this.H=b;this.L=function(a){if("SBI_SLOT_TARGETING"===a.data.key&&a.source)try{var b=Object.keys(d.D.R).map(function(a){return d.D.R[a]}).find(function(b){return b.fc===a.source.frameElement.id}).kb.Ja;a.source.postMessage({message:"SBI_HOLLABACK",macros:b},Object(m.h)())}catch(w){}};this.F=
l;this.H=b;this.C=this.C.bind(this);this.da=a;this.D=c;this.J=e}function l(a){"SAFE_FRAME_RENDER"===a.data.key&&a.source&&h.a.sbi_km.API.render(a.source,a.data.id,a.data.macros,a.origin)}function b(a){"SBI_KM_LOOKUP"===a.data.key&&a.source&&a.data.id===h.a.sbi_km.id&&a.source.postMessage({key:"SBI_KM_LOOKUP_RESPONSE"},a.origin)}var h=e(0),m=e(1);a.prototype.C=function(a){this.F(a);this.H(a);this.J.X.ga("enablePassback")&&this.L(a)};a.prototype.Bc=function(){h.a.addEventListener("message",this.C,!1)};
c.a=a}])})({url:"//mtrx.go.sonobi.com",adServer:"dfp",globalSettings:{sizes:"300x250 300x600 300x1050 300x50 320x50 320x100 728x90 160x600 120x600 970x250 970x90 300x100".split(" "),timeout:2E3,osEnabled:!1,priceRules:[{ge:1500,set:1500},{ge:900,lt:1500,round:5},{lt:900,round:1}]},adapterSettings:[{name:"sonobi",sizes:"300x250 300x600 300x1050 300x50 320x50 320x100 728x90 160x600 120x600 970x250 970x90 300x100".split(" "),timeout:1500,platforms:["mobile","desktop","tablet"],priceRules:[],parseSettings:[],
requestSettings:[{name:"hfa_cookie_key",value:"cbsiaa",dimensions:{sizes:[],adUnits:[],domains:[],platforms:[]}}]}],platformSettings:{mobile:{viewport:{lt:768}},tablet:{viewport:{ge:768,lt:992}},desktop:{viewport:{ge:992}}},analyticsSettings:{url:"https://keymaker.go.sonobi.com/keymaker",timeout:2E3}},"3.26.3");}).call(window);

//# sourceMappingURL=http://mtrx.go.sonobi.com/morpheus.247sports.2694.js.map